version: "3.4"

networks:
  freq_net:
    external: true

x-shared-deploy: &default-deploy
  mode: replicated
  replicas: 1
  placement:
    constraints:
      - node.role == manager
  restart_policy:
    condition: on-failure
    delay: 5s

x-service-template: &service-template
  image: freqtradeorg/freqtrade:develop_plot
  deploy:
    <<: *default-deploy
  volumes:
    - "./user_data:/freqtrade/user_data"
    - "./shared:/freqtrade/shared"
  environment:
    - PYTHONPATH=/freqtrade
  labels:
    - "traefik.enable=true"
    - "traefik.http.routers.freqcpd.entrypoints=http"
    - "traefik.http.routers.freqcpd.rule=Host(`cpd.freq.localhost`)"
    - "traefik.http.services.freqcpd.loadbalancer.server.port=8080"
    - "traefik.http.services.freqcpd.loadbalancer.sticky.cookie.name=cpdfreq"
  networks:
    - freq_net

services:

  cpd_1h:
    <<: *service-template
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy CPD1H

  cpd_4h:
    <<: *service-template
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy CPD4H

  cpd_1d:
    <<: *service-template
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy CPD1D
